/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.entity.validation

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class EntityValidator extends AbstractEntityValidator {

}
