/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.form.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FormUiModule extends at.ac.tuwien.big.forms.form.ui.AbstractFormUiModule {
	public FormUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.quickfix.IssueResolutionProvider> bindIssueResolutionProvider() {
		return at.ac.tuwien.big.forms.form.ui.quickfix.ocl.FormQuickfixProvider.class;
	}
}
