/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.form;

import org.eclipse.emf.ecore.EValidator;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;

import com.google.inject.Binder;

import at.ac.tuwien.big.forms.form.scoping.FormScopeProvider;
import at.ac.tuwien.big.oclgen.CustomRegistry;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FormRuntimeModule extends at.ac.tuwien.big.forms.form.AbstractFormRuntimeModule {
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		CustomRegistry.INSTANCE.registerCustom("http://www.big.tuwien.ac.at/forms", "at.ac.tuwien.big.forms.form.validation.");
		binder.requestInjection(CustomRegistry.INSTANCE);
		binder.bindListener(CustomRegistry.INSTANCE, CustomRegistry.INSTANCE);
	}

	@Override
	public EValidator.Registry bindEValidatorRegistry() {
		return CustomRegistry.INSTANCE;
	}
	
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return FormScopeProvider.class;
	}

//	@Override
//	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
//		return GlobalFormScopeProvider.class;
//	}

}
