/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.form.validation

import at.ac.tuwien.big.forms.form.validation.ocl.AttributeValidator
import at.ac.tuwien.big.forms.form.validation.ocl.CompositeConditionValidator
import at.ac.tuwien.big.forms.form.validation.ocl.ConditionValidator
import at.ac.tuwien.big.forms.form.validation.ocl.DateSelectionFieldValidator
import at.ac.tuwien.big.forms.form.validation.ocl.EntityValidator
import at.ac.tuwien.big.forms.form.validation.ocl.EnumerationValidator
import at.ac.tuwien.big.forms.form.validation.ocl.PageElementValidator
import at.ac.tuwien.big.forms.form.validation.ocl.RelationshipPageElementValidator
import at.ac.tuwien.big.forms.form.validation.ocl.RelationshipValidator
import at.ac.tuwien.big.forms.form.validation.ocl.SelectionFieldValidator
import at.ac.tuwien.big.forms.form.validation.ocl.TableValidator
import at.ac.tuwien.big.forms.form.validation.ocl.TimeSelectionFieldValidator
import org.eclipse.xtext.validation.ComposedChecks

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
 // TODO: Generate this?
@ComposedChecks(validators = #[ 
	AttributeValidator, CompositeConditionValidator, ConditionValidator,
	DateSelectionFieldValidator, EntityValidator, EnumerationValidator, at.ac.tuwien.big.forms.form.validation.ocl.FormValidator,
	PageElementValidator, RelationshipPageElementValidator, RelationshipValidator, SelectionFieldValidator, TableValidator,
	TimeSelectionFieldValidator
])
class FormValidator extends AbstractFormValidator {
	
}
